// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv`

interface CloudflareEnv {
	GAME_ROOM: DurableObjectNamespace<import("./worker/index").GameRoom>;
	ASSETS: Fetcher;
}
